name: Linter
on: [ push, pull_request ]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          src: "*"
          version: 0.0.292 
          args: --select B
